version: "3"
services:
  springBootApp:
    image: njktemp0/midproject:1.0
    container_name: docker-postgres-springboot-app
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-db
    ports:
      - "8091:8085"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure
  
  postgresDb:
    image: postgres:15.0
    container_name: docker-postgres-springboot-db
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Blastotron@5211
      - POSTGRES_DB=postgres
networks:
  network:
volumes:
  volume: