version: "3"
services:
  springBootApp:
    image: njktemp0/mproj:1.0
    container_name: docker-postgres-springboot-app
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-db
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Blastotron@5211
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8091:8085"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure
  
  postgresDb:
    image: postgres:15.0
    container_name: docker-postgres-springboot-db
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Blastotron@5211
      - POSTGRES_DB=postgres
networks:
  network:
volumes:
  volume: